name: Deploy Astro to GitHub Pages

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install node dependencies
        working-directory: ./web
        run: 
          npm install

      - name: Fetch content
        run: python ./script/get_content.py

      - name: Build Astro project
        run: python ./script/build_astro.py

      - name: Build the site
        working-directory: ./web
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./web/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}