name: Run tests, build and deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  deploy:
    name: Run full build and deployment
    uses: ./.github/workflows/deploy.yml